// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MottuWebApplication.Connection;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MottuWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MottuWebApplication.Models.Bairro", b =>
                {
                    b.Property<int>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBairro"));

                    b.Property<int>("IdCidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmBairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdBairro");

                    b.HasIndex("IdCidade");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmCidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("IdLogradouro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdLogradouro");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("DsDepartamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("NmDepartamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("IdPais")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmEstado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEstado");

                    b.HasIndex("IdPais");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Filial", b =>
                {
                    b.Property<int>("IdFilial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFilial"));

                    b.Property<int>("IdLogradouro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmFilial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdFilial");

                    b.HasIndex("IdLogradouro");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("MottuWebApplication.Models.FilialDepartamento", b =>
                {
                    b.Property<int>("IdFilialDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFilialDepartamento"));

                    b.Property<DateTime>("DtEntrada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DtSaida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdFilial")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdFilialDepartamento");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdFilial");

                    b.ToTable("FilialDepartamentos");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("IdFilial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmCargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("NmEmailCorporativo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NmFuncionario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NmSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdFilial");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Logradouro", b =>
                {
                    b.Property<int>("IdLogradouro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogradouro"));

                    b.Property<int>("IdBairro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmComplemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NmLogradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NrLogradouro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("IdLogradouro");

                    b.HasIndex("IdBairro");

                    b.ToTable("Logradouros");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Manutencao", b =>
                {
                    b.Property<int>("IdManutencao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManutencao"));

                    b.Property<string>("DsManutencao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<DateTime>("DtEntrada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DtSaida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdManutencao");

                    b.HasIndex("IdMoto");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<string>("NmModelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdModelo");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdFilialDepartamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdModelo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("KmRodado")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("NmPlaca")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("StMoto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("IdMoto");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdFilialDepartamento");

                    b.HasIndex("IdModelo");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("NmPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Bairro", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Cidade", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Cliente", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Logradouro", "Logradouro")
                        .WithMany("Clientes")
                        .HasForeignKey("IdLogradouro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Estado", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Filial", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Logradouro", "Logradouro")
                        .WithMany("Filiais")
                        .HasForeignKey("IdLogradouro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("MottuWebApplication.Models.FilialDepartamento", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MottuWebApplication.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Funcionario", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Logradouro", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Manutencao", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Moto", b =>
                {
                    b.HasOne("MottuWebApplication.Models.Cliente", "Cliente")
                        .WithMany("Motos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MottuWebApplication.Models.FilialDepartamento", "FilialDepartamento")
                        .WithMany()
                        .HasForeignKey("IdFilialDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MottuWebApplication.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("FilialDepartamento");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Cliente", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("MottuWebApplication.Models.Logradouro", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Filiais");
                });
#pragma warning restore 612, 618
        }
    }
}
